### ISSUE TITLE
Allow Deletion of File

### ISSUE THREAD

**Issue by EAnushan** [mongosoft/yii2-upload-behavior#3]
There is no way to explicitly remove a file. If a file is not submitted, we protect the attribute so it doesn't change. If a file is submitted, we optionally delete the old file and upload the new one.

I propose the following enhancement:

If the attribute is submitted as the string "deleted", then we will delete the uploaded file. This will still allow  upload of any file, including files named "deleted", since those will automatically be transformed into an instance of ```UploadedFile``` in the beforeValidate handler.

**Comment by ufocoder** [comment]
As I understand your issue you want to delete upload file. 
You can run `getUploadPath` method to get file path, then `unlink` file and set model's attribute is `null`. Is It not enough?

**Comment by EAnushan** [comment]
You can't tell when a file is deleted from the front end. So a front end control, such as an image picker, has no way of communicating to yii2-upload-behavior that the file should be deleted. The front end image picker generally does not submit the image name if it is left unchanged. When an image is deleted, I propose that front end image pickers may submit the "deleted" string and yii2-upload-behavior will delete the file.

**Comment by EAnushan** [comment]
I'm guessing this feature is not getting in?

**Comment by mongosoft** [comment]
You can delete a file such as:

```php

$model = new User();
// $model->setScenario('default'); // upload bahavior uses only within save or update scenarion
$model->image = null;

$model->save();

Or, for example, disconnect behavior on the fly.

**Comment by jplozgom** [comment]
Hi, thanks for the great extension, and please forgive me for commenting in a closed issue. 

I was trying to implement an option when the user can delete a file or image when desired by checking a checkbox (this would be the flag that indicates if a file should be deleted ). When I saw you comment of setting this attribute to null I realized that it is a good idea but then I saw that it  won't work because the selected attribute is protected on line 165  of UploadBehavior. Then I added the following

                $attribute = $this->attribute;
                // Protect attribute if the attribute has not been set to null
                if (!is_null($model->$attribute)) {
                    unset($model->{$this->attribute});
                }

With this modification it works great. Please take into account that if you only have one attribute in your model using this behavior you could set the attribute to null and change scenario to default and it will delete the file (as long as you have the unlinkOnSave on true, in my case I had multiple attributes using the behavior and all the files where deleted with the scenario change and thats why I made the change on line 165 of UploadBehavior). 

Please let me know if you agree with this approach and we could add it.
